#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
DIST_DIRECTORY="$PROJECT_ROOT/dist"
SITE_DOMAIN="terrarium.arrangedgodly.com"

can_run_pnpm() {
  if command -v pnpm >/dev/null 2>&1; then
    return
  fi

  command -v powershell.exe >/dev/null 2>&1 || return 1
  powershell.exe -NoProfile -Command "if (Get-Command pnpm -ErrorAction SilentlyContinue) { exit 0 }; exit 1" >/dev/null 2>&1
}

run_build() {
  if command -v pnpm >/dev/null 2>&1; then
    (cd "$PROJECT_ROOT" && pnpm build)
    return
  fi

  if command -v powershell.exe >/dev/null 2>&1 && command -v cygpath >/dev/null 2>&1; then
    local project_root_windows
    project_root_windows=$(cygpath -w "$PROJECT_ROOT")
    note "pnpm is not on the Bash PATH; building through PowerShell instead."
    if powershell.exe -NoProfile -Command "Set-Location -LiteralPath '$project_root_windows'; pnpm build"; then
      return
    fi
  fi

  if [[ -f "$DIST_DIRECTORY/index.html" ]]; then
    warn "pnpm is not available in this terminal. Continuing with the existing verified dist/ build."
    note "To publish later code changes, install Node.js/pnpm locally or rebuild through Codex before running this wizard."
    return
  fi

  warn "pnpm is not available and dist/index.html is missing. Install Node.js with Corepack/pnpm, then re-run this wizard."
  return 1
}

banner "Cloudflare Pages · Algorithmic Terrarium"

stage "Build the static site"
say "Cloudflare Pages will receive only the static files in dist/. No credentials are needed."
if can_run_pnpm; then
  step "This wizard can rebuild the site now, so the upload contains the latest version."
  if confirm "Run pnpm build now?"; then
    run_build
  fi
else
  warn "pnpm is not installed in this terminal, so this run will use the existing verified dist/ build."
  note "Install Node.js/pnpm before a future deployment that includes source changes."
fi
if [[ ! -f "$DIST_DIRECTORY/index.html" ]]; then
  warn "dist/index.html is missing. Run 'pnpm build' from $PROJECT_ROOT, then re-run this wizard."
  exit 1
fi
note "Upload folder: $DIST_DIRECTORY"
pause "Press Enter once dist/ is ready to upload."

stage "Create the Pages project and upload dist"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "In Workers & Pages, choose Create application → Get started → Drag and drop your files."
step "Name the project 'algorithmic-terrarium' (or another available name)."
step "Drag the complete dist folder shown above into the upload area, then select Deploy site."
note "The first deployment receives a temporary <project>.pages.dev address."
pause "Press Enter after Cloudflare reports that the deployment succeeded."

stage "Associate $SITE_DOMAIN"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the Pages project you just deployed, then choose Custom domains → Set up a domain."
step "Enter $SITE_DOMAIN, continue, and confirm/activate the domain."
warn "Do not add a CNAME first. Associate the custom domain from the Pages project before creating or accepting DNS records."
step "If arrangedgodly.com is a Cloudflare zone in this account, accept Cloudflare's DNS record. Otherwise create the CNAME Cloudflare shows, pointing to your assigned <project>.pages.dev hostname."
pause "Press Enter after the custom-domain status is Active."

stage "Verify the live terrarium"
open_url "https://$SITE_DOMAIN"
step "Confirm the page title is 'The Algorithmic Terrarium' and the first plant appears."
step "Move an environment slider, select Grow plant, then select Reset defaults."
step "Confirm the browser shows HTTPS without a certificate warning. DNS and certificate activation can take a few minutes."
if confirm "Is https://$SITE_DOMAIN live and working?"; then
  say "Your Algorithmic Terrarium is live at https://$SITE_DOMAIN"
else
  warn "Wait a few minutes and check the Pages deployment and Custom domains status."
  note "Cloudflare guide: https://developers.cloudflare.com/pages/configuration/custom-domains/"
fi

finish
